Update JDK versions

diff --git a/kotlin/ze-space/Dockerfile b/kotlin/ze-space/Dockerfile
--- a/kotlin/ze-space/Dockerfile
+++ b/kotlin/ze-space/Dockerfile
@@ -1,12 +1,19 @@
+# Fails to run Gradle on alpine due to javax.net.ssl.SSLHandshakeException
 FROM eclipse-temurin:8-jdk-jammy AS builder
 
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends patch && \
-    rm -rf /var/lib/apt/lists/*
 WORKDIR /space
 COPY space jar.patch ./
-RUN patch -p1 -i jar.patch && \
-    ./gradlew jar
+RUN <<EOF
+set -e
+
+apt-get update
+apt-get install -y --no-install-recommends patch
+rm -rf /var/lib/apt/lists/*
+
+patch -p1 -i jar.patch
+./gradlew jar
+
+EOF
 
 FROM eclipse-temurin:21-jre-alpine
 
