all: Automatically convert Dockerfile to Earthfile

diff --git a/kotlin/ze-space/Earthfile b/kotlin/ze-space/Earthfile
--- a/kotlin/ze-space/Earthfile
+++ b/kotlin/ze-space/Earthfile
@@ -1,22 +1,23 @@
-# Fails to run Gradle on alpine due to javax.net.ssl.SSLHandshakeException
-FROM eclipse-temurin:8-jdk-jammy AS builder
+VERSION 0.8
 
-WORKDIR /space
-COPY space jar.patch ./
-RUN <<EOF
-set -e
+build:
+    # Fails to run Gradle on alpine due to javax.net.ssl.SSLHandshakeException
+    FROM eclipse-temurin:8-jdk-jammy
+    WORKDIR /space
+    COPY space jar.patch ./
+    RUN set -e \
+        \
+        apt-get update \
+        apt-get install -y --no-install-recommends patch \
+        rm -rf /var/lib/apt/lists/* \
+        \
+        patch -p1 -i jar.patch \
+        ./gradlew jar
+    SAVE ARTIFACT build/libs/space.jar /bin/
 
-apt-get update
-apt-get install -y --no-install-recommends patch
-rm -rf /var/lib/apt/lists/*
-
-patch -p1 -i jar.patch
-./gradlew jar
-
-EOF
-
-FROM eclipse-temurin:21-jre-alpine
-
-WORKDIR /space
-COPY --from=builder /space/build/libs/space.jar .
-ENTRYPOINT ["java", "-jar", "space.jar"]
+docker:
+    FROM eclipse-temurin:21-jre-alpine
+    WORKDIR /space
+    COPY +build/ .
+    ENTRYPOINT ["java", "-jar", "bin/space.jar"]
+    SAVE IMAGE wspace-corpus/kotlin/ze-space
